export const types = {
  INITIAL_LISTS_LOADED: 'INITIAL_LISTS_LOADED',
  NEW_LIST_SAVED: 'NEW_LIST_SAVED',
  UPDATED_LIST_SAVED: 'UPDATED_LIST_SAVED',
  LIST_DELETED: 'LIST_DELETED',
  LIST_SELECTED: 'LIST_SELECTED',
  TITLE_UPDATED: 'TITLE_UPDATED',
};
